package com.aws.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Product")
public class Product  {

	@DynamoDBHashKey(attributeName = "productId")
	@DynamoDBAutoGeneratedKey
	private String productId;
	@DynamoDBAttribute
	private String name;
	@DynamoDBAttribute
	private double price;
	@DynamoDBAttribute
	private String review;
	
}
